/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.PhoneNumberBL;

/**
 *
 * @author SF
 */
public class PhoneNumberGUI extends javax.swing.JFrame {

  /**
   * Creates new form TelNumberGUI
   */
  public PhoneNumberGUI() {
    initComponents();
    this.setSize(400,300);
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    tfNumber = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    taOutput = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.BorderLayout(3, 3));

    jPanel1.setLayout(new java.awt.GridLayout(2, 1, 3, 3));

    tfNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    tfNumber.setBorder(javax.swing.BorderFactory.createTitledBorder("phone number"));
    jPanel1.add(tfNumber);

    jPanel2.setLayout(new java.awt.GridLayout(1, 2, 3, 3));

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jButton1.setText("create number");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onCreateNumber(evt);
      }
    });
    jPanel2.add(jButton1);

    jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jButton2.setText("check number");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onCheckNumber(evt);
      }
    });
    jPanel2.add(jButton2);

    jPanel1.add(jPanel2);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    taOutput.setColumns(20);
    taOutput.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    taOutput.setRows(5);
    jScrollPane1.setViewportView(taOutput);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onCreateNumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateNumber
    tfNumber.setText(PhoneNumberBL.createPhoneNumber());
  }//GEN-LAST:event_onCreateNumber

  private void onCheckNumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCheckNumber
    String number = tfNumber.getText();
    String result = number + " - ";
    try {
      if (PhoneNumberBL.checkPhoneNumber(number)) {
        String area = PhoneNumberBL.getArea(number);
        if (area.equals("Mobil")) {
          result += String.format("valid mobile number\n");
        } else {
          result += String.format("valid number from %s \n", area);
        }
      } else {
        result += "invalid number !\n";
      }
    } catch (Exception e) {
      result += "Illegal number !!!\n";
    }
    taOutput.append(result);
  }//GEN-LAST:event_onCheckNumber

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(PhoneNumberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(PhoneNumberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(PhoneNumberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(PhoneNumberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PhoneNumberGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea taOutput;
  private javax.swing.JTextField tfNumber;
  // End of variables declaration//GEN-END:variables
}
